### ISSUE TITLE
Error on splitting map Linux version

### ISSUE THREAD

**Issue by settantahertz** [treellama/atque#2]
I have an error while I try to split a .sceA file (tried with Marathon2 and Marathon Infinity maps).
The error I have in the terminal is
```
free(): double free detected in tcache 2
Annullato (core dump creato) [translation: Canceled (core dump created)]
```

I'm on Linux Mint 20 Mate, derivative from Ubuntu Focal Fossa
I'm also working on a virtual machine installed on Virtualbox

The steps to build Atque:
- download atque.zip from master branch
- installed needed and suggested libraries, the version I have in synaptic (libsndfile1, boost libraries 1.71, wxwidgets 3.0)
- built with _./autoconf.sh_, then _./configure_, then _make_

Atque starts correctly
Images.imgA files split and merge correctly
The error appear only on .sceA files, when saving (save window appear, then I save, then Atque quits with the error, nothing is saved).

Let me know if missing info is needed (I don't really know how to check for specific logs, in example)

**Comment by treellama** [comment]
Would you give aa5482d a try?

**Comment by settantahertz** [comment]
It works! Tried splitting and mergin Infinity Map.
