### ISSUE TITLE
Splitting image files doesn't appear to work on Windows

### ISSUE THREAD

**Issue by ReindeerFloatilla** [treellama/atque#7]
I attempted to use Atque on Windows 11 on Marathon Infinity's imgA file. However the folder it outputs into is empty. Is this a bug or is there another step I'm missing?

https://github.com/treellama/atque/assets/24368041/74b2c3c0-1fa0-48c7-9daa-a8dba916a2c1

**Comment by treellama** [comment]
Turns out this was because the images being distributed were in a format Atque doesn't understand. You should be able to split the image files that come with the 1.10 release again.
